# constants
BOARD_SIZE = 7
MIN_COLUMN_SIZE = 0
MAX_COLUMN_SIZE = 6
DEFAULT_VALUE = '='
COMPUTER = 'C'
HUMAN = 'P'
COMPUTER_WIN = 1
PLAYER_WIN = -1
TIE = 0
DEFAULT_DEPTH = 5
FULL_COLUMN = '-'
FORMATTING = "{:.3f}"
